version: "3.8"
services: 
  backend:
    build: .
    ports: 
      - '80:80'
    volumes:
      - ./dist:/app
      - /app/node_modules
    env_file:
      - ./config.env
  frontend:
    build: ./client
    ports: 
      - '3000:3000'
    volumes: 
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend

